### ISSUE TITLE
Order of search results

### ISSUE THREAD

**Issue by madebr** [libsdl-org/ghwikipp#60]
> the wiki search function favors SDL2 over SDL3, also, I guess it would be nice if exact matches were at the top.

![image](https://github.com/user-attachments/assets/aea0dd15-4946-4b3f-a4f1-ba004f120f47)

(From discord)

**Comment by icculus** [comment]
Okay, this now favors SDL3 over SDL2 in general, and exact page names are sorted first...so [a search for SDL_CreateWindow](https://wiki.libsdl.org/wiki/search?q=SDL_CreateWindow) will report [SDL3/SDL_CreateWindow](https://wiki.libsdl.org/SDL3/SDL_CreateWindow), then [SDL2/SDL_CreateWindow](https://wiki.libsdl.org/SDL2/SDL_CreateWindow), then all SDL3 pages that mention it, then all SDL2 pages. This is all case-insensitive, too.

This works for the satellite libraries, too, because they all have subdirectories that start with "SDL2" or "SDL3" in the wiki.

[mix_openaudio](https://wiki.libsdl.org/wiki/search?q=mix_openaudio), for example.
